### ISSUE TITLE
There is a hard dependency on oUnit somewhere

### ISSUE THREAD

**Issue by djs55** [mirage/functoria#67] opened 2016-07-27 10:11 UTC
On a relatively clean `opam install mirage`: (I've got some unreleased testing `mirage-types` and `mirage-types-lwt` packages in this list)

```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
∗  installed conf-ncurses.1+system
∗  installed conf-m4.1
∗  installed result.1.2
∗  installed ocamlbuild.0.9.2
∗  installed ocamlfind.1.6.2
∗  installed base-bytes.base
∗  installed cmdliner.0.9.8
∗  installed astring.0.8.1
∗  installed cppo.1.3.2
∗  installed ppx_tools.5.0+4.03.0
∗  installed ocamlgraph.1.8.7
∗  installed ocplib-endian.1.0
∗  installed sexplib.113.33.00+4.03
∗  installed ppx_deriving.3.3
∗  installed topkg.0.7.7
∗  installed rresult.0.4.0
∗  installed fmt.0.8.0
[ERROR] The compilation of functoria failed at "ocaml pkg/pkg.ml build --pinned
        false".
∗  installed lwt.2.5.2
∗  installed logs.0.6.1
∗  installed ppx_core.113.33.01+4.03
∗  installed cstruct.2.2.0
∗  installed ppx_optcomp.113.33.00+4.03
∗  installed io-page.1.6.1
∗  installed ppx_driver.113.33.01+4.03
∗  installed ppx_type_conv.113.33.01+4.03
∗  installed ppx_sexp_conv.113.33.01+4.03
∗  installed ipaddr.2.7.0
∗  installed mirage-types.2.9.0
∗  installed mirage-types-lwt.2.9.0

#=== ERROR while installing functoria.1.2.0 ===================================#
# opam-version 1.2.2
# os           darwin
# command      ocaml pkg/pkg.ml build --pinned false
# path         /Users/djs/.opam/system/build/functoria.1.2.0
# compiler     system (4.03.0)
# exit-code    1
# env-file     /Users/djs/.opam/system/build/functoria.1.2.0/functoria-72523-ed04f4.env
# stdout-file  /Users/djs/.opam/system/build/functoria.1.2.0/functoria-72523-ed04f4.out
# stderr-file  /Users/djs/.opam/system/build/functoria.1.2.0/functoria-72523-ed04f4.err
### stdout ###
# [...]
# ocamlfind ocamlopt -c -g -bin-annot -safe-string -short-paths -keep-locs -strict-sequence -package cmdliner -package fmt -w A-40-42-44 -warn-error +1..49 -warn-error -45-3 -package bytes -I runtime -I lib -I app -o runtime/functoria_info.cmx runtime/functoria_info.ml
# ocamlfind ocamlopt -a -package cmdliner -package fmt -dontlink unix -dontlink unix -package bytes runtime/functoria_runtime.cmx runtime/functoria_info.cmx -o runtime/functoria-runtime.cmxa
# ocamlfind ocamlopt -shared -linkall -package cmdliner -package fmt -dontlink unix -dontlink unix -package bytes runtime/functoria-runtime.cmxa -o runtime/functoria-runtime.cmxs
# ocamlfind ocamlc -c -g -bin-annot -safe-string -short-paths -keep-locs -strict-sequence -package cmdliner -package fmt -w A-40-42-44 -warn-error +1..49 -warn-error -45-3 -package bytes -I runtime -I lib -I app -o runtime/functoria_runtime.cmo runtime/functoria_runtime.ml
# ocamlfind ocamlc -c -g -bin-annot -safe-string -short-paths -keep-locs -strict-sequence -package cmdliner -package fmt -w A-40-42-44 -warn-error +1..49 -warn-error -45-3 -package bytes -I runtime -I lib -I app -o runtime/functoria_info.cmo runtime/functoria_info.ml
# ocamlfind ocamlc -a -package cmdliner -package fmt -dontlink unix -dontlink unix -package bytes runtime/functoria_runtime.cmo runtime/functoria_info.cmo -o runtime/functoria-runtime.cma
# ocamlfind ocamldep -package oUnit -package cmdliner -package fmt.cli -package rresult -package bytes -modules tests/test_functoria_command_line.ml > tests/test_functoria_command_line.ml.depends
# + ocamlfind ocamldep -package oUnit -package cmdliner -package fmt.cli -package rresult -package bytes -modules tests/test_functoria_command_line.ml > tests/test_functoria_command_line.ml.depends
# ocamlfind: Package `oUnit' not found
# Command exited with code 2.
### stderr ###
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-tag' 'debug'
# [...]
#      'app/functoria_graph.mli' 'app/functoria_command_line.cmx'
#      'app/functoria_command_line.cmi' 'app/functoria_command_line.mli'
#      'app/functoria_app.cmx' 'app/functoria_app.cmi' 'app/functoria_app.mli'
#      'runtime/functoria-runtime.a' 'runtime/functoria-runtime.cmxs'
#      'runtime/functoria-runtime.cmxa' 'runtime/functoria-runtime.cma'
#      'runtime/functoria_info.cmx' 'runtime/functoria_info.cmi'
#      'runtime/functoria_info.mli' 'runtime/functoria_runtime.cmx'
#      'runtime/functoria_runtime.cmi' 'runtime/functoria_runtime.mli'
#      'tests/test_functoria_command_line.native']: exited with 10



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions were aborted
  ∗  install mirage 2.10.0
The following actions failed
  ∗  install functoria 1.2.0
The following changes have been performed
  ∗  install astring          0.8.1
  ∗  install base-bytes       base
  ∗  install cmdliner         0.9.8
  ∗  install conf-m4          1
  ∗  install conf-ncurses     1+system
  ∗  install cppo             1.3.2
  ∗  install cstruct          2.2.0
  ∗  install fmt              0.8.0
  ∗  install io-page          1.6.1
  ∗  install ipaddr           2.7.0
  ∗  install logs             0.6.1
  ∗  install lwt              2.5.2
  ∗  install mirage-types     2.9.0
  ∗  install mirage-types-lwt 2.9.0
  ∗  install ocamlbuild       0.9.2
  ∗  install ocamlfind        1.6.2
  ∗  install ocamlgraph       1.8.7
  ∗  install ocplib-endian    1.0
  ∗  install ppx_core         113.33.01+4.03
  ∗  install ppx_deriving     3.3
  ∗  install ppx_driver       113.33.01+4.03
  ∗  install ppx_optcomp      113.33.00+4.03
  ∗  install ppx_sexp_conv    113.33.01+4.03
  ∗  install ppx_tools        5.0+4.03.0
  ∗  install ppx_type_conv    113.33.01+4.03
  ∗  install result           1.2
  ∗  install rresult          0.4.0
  ∗  install sexplib          113.33.00+4.03
  ∗  install topkg            0.7.7

The former state can be restored with:
    opam switch import "~/.opam/system/backup/state-20160627100450.export"
```

If I clone latest master (a3c5d3b6609d98a03eba114eb4f0edd03e4024c6) and type `make` I get the same error. The `opam` file claims `ounit` is a test dependency but I suspect this isn't true at the moment.

The problem is fixed if I pre-install `ounit`.

**Comment by hannesm** [comment] 2016-07-27 10:36
I ran into the same... why is `test_functoria_command_line` even built? @samoht @dbuenzli (`pkg.ml` contains `Pkg.test "tests/test_functoria_command_line";` (which afaiu should only be built when `tests true` is passed via commandline))

**Comment by dbuenzli** [comment] 2016-07-27 16:25
Where do you get this functoria 1.2.0 from ? I get only 1.1.0.

**Comment by dbuenzli** [comment] 2016-07-27 16:29
(That said I checked the code in topkg and tested with another package that has tests (`fpath`) and it should work). Where is the tarball for that 1.2.0 ?

**Comment by hannesm** [comment] 2016-07-27 16:39
1.2.0 is in the mirage-dev repository [here](https://github.com/mirage/mirage-dev/tree/master/packages/functoria/functoria.1.2.0), pointing to functoria's git master

**Comment by samoht** [comment] 2016-07-27 18:24
functoria needs ounit to build the tests. I probably forgot something while topkging it.

**Comment by dbuenzli** [comment] 2016-07-27 18:50
> 1.2.0 is in the mirage-dev repository here, pointing to functoria's git master

So there's no tarball, no release, and nothing was actually broken. 

If the `.git` repository of functoria is present in the build dir (don't know how git packages are handled) you will get a `Dev` build (see  [`build_context`](http://erratique.ch/software/topkg/doc/Topkg.Conf.html#VALbuild_context for details)) in which case the [`build_tests`](http://erratique.ch/software/topkg/doc/Topkg.Conf.html#VALbuild_tests) key will default to true.  

Invoking the install with `TOPKG_VERBOSITY=debug opam install functoria -v` should give more info about what exactly is inferred (see `topkg help trouble` when you get into trouble with `topkg`).

**Comment by samoht** [comment] 2016-07-27 19:00
so should I add a `"oUnit" {dev}` constraint in the opam file?

**Comment by dbuenzli** [comment] 2016-07-27 19:12
I don't think `dev` does anything in current opam.

**Comment by yomimono** [comment] 2016-07-27 19:28
It seems like we'd get a different (non-test) build if `pinned` were true, which reflects better what's actually going on - we're referring to a remote which has the effect of giving us a whole bunch of packages `git`-pinned to master.  Can we easily make that be true?

**Comment by dbuenzli** [comment] 2016-07-27 19:30
I think this should be discussed with @AltGr but I think that git-packages should have `pinned` set to `true`. They behave exactly like `pins` and the same set of actions (watermarking, checkout massaging) has to be peformed on them and I don't think it's worth introducing a new build context for this case.

@yomimono you can simply say `"--pinned" "true"` instead of `--pinned pinned` in the OPAM file of the mirage-dev repository.

**Comment by Drup** [comment] 2016-07-27 21:38
> so should I add a "ounit" {dev} constraint in the opam file?

No, the solution is to fix whatever topkg is doing. oUnit is a test dependency, not a dev one. The fact that test are automatically enabled for git packages is a bug.

**Comment by AltGr** [comment] 2016-07-28 08:08
@dbuenzli there is already, internally, a notion of `dev` packages, that are bound to VC remotes. This is needed e.g. when running `opam update`, and is what the `{dev}` dependency flag is bound to. There is no package-level variable with this information, though, so we should probably expand the scope of `dev`.

**Comment by yomimono** [comment] 2016-07-28 11:06
@dbuenzli I'd expect the right place to set `--pinned` to `true` would be in the `build` list of the `opam` file, but having done that, we still get compilation with `--pinned` set to `false`: https://travis-ci.org/mirage/mirage/jobs/147781612#L735

**Comment by yomimono** [comment] 2016-07-28 13:04
Please disregard my last comment; the branch of mirage-dev pinned there wasn't the current master.

**Comment by dbuenzli** [comment] 2016-07-28 13:05
@yomimono Still it may actually pick up the opam file of the `git` repo so it may not work.

**Comment by dbuenzli** [comment] 2016-07-28 13:11
So simply adding `--tests false` in every OPAM file out there should solve this problem.

@AltGr what about having `pinned` set to `true` for git-packages ? Or any other variable that would be `true` for both `pin`s and `git` packages.

**Comment by AltGr** [comment] 2016-07-28 13:44
Currently `dev` packages are defined almost, but not exactly like that: they are packages that require being pulled on every `opam update`, _i.e._ unpinned packages with a `http` remote, or otherwise (unpinned but with a VC remote, or pinned) packages with no checksum specified. If one is to pin a package to an http remote with a checksum, that probably won't need to be treated as a `dev` package

A `dev` variable is already defined, but only in the scope of dependency filters (`depends: foo {here & <="3"}`). Wouldn't extending its scope to the build/install/etc instructions be sufficient for your need ?

**Comment by dbuenzli** [comment] 2016-07-28 15:41
> A dev variable is already defined, but only in the scope of dependency filters (depends: foo {here & <="3"}). Wouldn't extending its scope to the build/install/etc instructions be sufficient for your need ?

Not really, people would have to write something like `--pinned (dev || pinned)` which I don't expect to work in build instructions and is needlessly long winded.

I would much prefer if vcs dev packages were able to advertise themselves as a pin (which AFAIU is behavouraly exactly what they are) and had the `pinned` variable set. As I said above there's no need to invent a new build context for that particular case.

**Comment by Drup** [comment] 2016-07-28 15:50
So, stop me if I'm wrong, but if I understand correctly: 
- when topkg detects a vcs, the build is in mode "dev"
- When in mode "dev", tests are automatically run.

Can we just remove the last part ? It's personally not something I want, I just want a "make test" command that will do what I expect it to do (run the tests) and a "make" command that will .. not run the tests. Apparently I'm not the only one to find that behavior surprising.

**Comment by dbuenzli** [comment] 2016-07-28 16:06
@Drup Two things:

1. The problem is beyond test. `topkg` supports workflows where a function has to be applied on a checkout to make it an installable distribution (one example is to download the ucd database and generate optimal data structures for an `uucp` distribution, another one is to peform the version watermarking). When a repo is pinned (or is a vcs dev package) you have to apply this function in order for the checkout to be installable. So I need to be able to detect when this is the case (the notion of [build context](http://erratique.ch/software/topkg/doc/Topkg.Conf.html#VALbuild_context)).

2. Your understanding is slightly wrong. In `Dev` mode (which is expected to be determined only when you hack on a repo checkout --- as we see it's not at the moment...), tests are automatically *built* on `topkg build` but not run (there's another command for that), if you are not happy about this you can inhibit it by calling `topkg build --tests false`. I have the feeling that this is a right default but if you think it's not, file an issue on topkg so that we can gather feedback.

**Comment by Drup** [comment] 2016-07-28 16:20
I see. That's less unreasonable, but I still would prefer no such autodetection, and simply having an argument. The topkg command line is usually invoked by opam or a make file, having an explicite argument is not a problem.

**Comment by AltGr** [comment] 2016-07-28 17:17
>  people would have to write something like --pinned (dev || pinned)

I am not sure I follow: having a package build depend on whether the source is a release tarball or a dev upstream seems a normal case for me, and is what the `dev` variable is supposed to be about; but I don't understand why you would want to depend on the fact that it is pinned there, there are many reasons for pinning that aren't related to a dev upstream at all ?

**Comment by dbuenzli** [comment] 2016-07-28 19:01
So does the implication `pinned => dev` hold ?

**Comment by AltGr** [comment] 2016-08-02 08:00
No, you can _e.g._ pin to some older version and use the repository package which has no reason to be considered `dev`. You can also pin to alter (fix) some fields in the opam file without changing the upstream.

`dev` depends only on the upstream URL, while pinned depends on a user operation (which is, most often, used to alter the upstream URL, hence the confusion)

**Comment by dbuenzli** [comment] 2016-08-02 08:54
Right so the usage of the `pinned` variable by `topkg` packages is clearly wrong. Now please review [point 1.](https://github.com/mirage/functoria/issues/67#issuecomment-235942630) of this comment, which mecanism does OPAM provide me to detect such a build context ?

**Comment by dbuenzli** [comment] 2016-08-02 09:06
> Right so the usage of the pinned variable by topkg packages is clearly wrong.

Well not *totally* since it also relies on the presence of the `.git` dir.

**Comment by yomimono** [comment] 2016-11-05 01:06
This isn't really a functoria issue, so I'm closing this issue; please feel free to reopen if you think functoria itself still needs to change in some way.

**Closed by yomimono** 2016-11-05 01:06 UTC
